# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Bad Labs
description: Experimenting with mobile apps (and other things)
url: https://bad-labs.com # the base hostname AND PROTOCOL for your site, e.g. http://example.com

content_type: # Define whether this is a knowledge base, help center, or something else
use_authors: true #Set this to false to disable showing post authors

brand_logo: logo.png
brand_name: Bad Labs
header: Mobile app experiments
subheader: Android and iOS native development

# Social Links
twitter_username:
facebook_page:
github_username: bad-labs-apps
email: bad.labsl.dev@gmail.com
linkedin_page:
instagram_username: 


# Navivation
nav_item_one: Github
nav_item_one_link: https://github.com/bad-labs-apps

nav_item_two: #
nav_item_two_link: #

nav_item_three: #
nav_item_three_link: #

nav_button: Download Apod
nav_button_link: https://github.com/bad-labs-apps

# More Help
help_one_title: Found a bug?
help_one_content: If you find any problems with our apps, please open an issue over on Github.
help_one_button: Github
help_one_link: https://github.com/orgs/bad-labs-apps/repositories

help_two_title: Reach out the dev!
help_two_content: Feel free to drop me a message directly with suggestions for our apps 👋.
help_two_button: psimao
help_two_link: https://psimao.dev

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#

sass:
  sass_dir:          _scss
  style:            :compressed
